export const DEFAULT_LOCALE = 'en';
export const CHANGE_LOCALE = 'app/LanguageToggle/CHANGE_LOCALE';

// USER AUTH MODULE
export const USER_LOGGED_IN = 'AUTH:USER_LOGGED_IN';
export const USER_LOGGED_IN_FAILED = 'AUTH:USER_LOGGED_IN_FAILED';
export const USER_LOGGED_IN_SUCCESS = 'AUTH:USER_LOGGED_IN_SUCCESS';
export const USER_LOGGED_OUT = 'AUTH:USER_LOGGED_OUT';
export const USER_FORGOT = 'AUTH:USER_FORGOT';
export const USER_FORGOT_FAILED = 'AUTH:USER_FORGOT_FAILED';
export const USER_FORGOT_SUCCESS = 'AUTH:USER_FORGOT_SUCCESS';
export const USER_RESET = 'AUTH:USER_RESET';
export const USER_RESET_FAILED = 'AUTH:USER_RESET_FAILED';
export const USER_RESET_SUCCESS = 'AUTH:USER_RESET_SUCCESS';

// USER MODULE
export const USER_LOAD = 'USER:LOAD';
export const USER_LOAD_SUCCESS = 'USER:LOAD_SUCCESS';
export const USER_LOAD_FAILED = 'USER:LOAD_FAILED';
export const USER_CREATE = 'USER:CREATE';
export const USER_CREATE_SUCCESS = 'USER:CREATE_SUCCESS';
export const USER_CREATE_FAILED = 'USER:CREATE_FAILED';
export const USER_UPDATE = 'USER:UPDATE';
export const USER_UPDATE_SUCCESS = 'USER:UPDATE_SUCCESS';
export const USER_UPDATE_FAILED = 'USER:UPDATE_FAILED';
export const USER_DELETE = 'USER:DELETE';
export const USER_DELETE_SUCCESS = 'USER:DELETE_SUCCESS';
export const USER_DELETE_FAILED = 'USER:DELETE_FAILED';

// SERVICE MODULE
export const SERVICE_LOAD = 'SERVICE:LOAD';
export const SERVICE_LOAD_SUCCESS = 'SERVICE:LOAD_SUCCESS';
export const SERVICE_LOAD_FAILED = 'SERVICE:LOAD_FAILED';
export const SERVICE_CREATE = 'SERVICE:CREATE';
export const SERVICE_CREATE_SUCCESS = 'SERVICE:CREATE_SUCCESS';
export const SERVICE_CREATE_FAILED = 'SERVICE:CREATE_FAILED';
export const SERVICE_UPDATE = 'SERVICE:UPDATE';
export const SERVICE_UPDATE_SUCCESS = 'SERVICE:UPDATE_SUCCESS';
export const SERVICE_UPDATE_FAILED = 'SERVICE:UPDATE_FAILED';
export const SERVICE_DELETE = 'SERVICE:DELETE';
export const SERVICE_DELETE_SUCCESS = 'SERVICE:DELETE_SUCCESS';
export const SERVICE_DELETE_FAILED = 'SERVICE:DELETE_FAILED';

// BILLING_CYCLE MODULE
export const BILLING_CYCLE_LOAD = 'BILLING_CYCLE:LOAD';
export const BILLING_CYCLE_LOAD_SUCCESS = 'BILLING_CYCLE:LOAD_SUCCESS';
export const BILLING_CYCLE_LOAD_FAILED = 'BILLING_CYCLE:LOAD_FAILED';
export const BILLING_CYCLE_CREATE = 'BILLING_CYCLE:CREATE';
export const BILLING_CYCLE_CREATE_SUCCESS = 'BILLING_CYCLE:CREATE_SUCCESS';
export const BILLING_CYCLE_CREATE_FAILED = 'BILLING_CYCLE:CREATE_FAILED';
export const BILLING_CYCLE_UPDATE = 'BILLING_CYCLE:UPDATE';
export const BILLING_CYCLE_UPDATE_SUCCESS = 'BILLING_CYCLE:UPDATE_SUCCESS';
export const BILLING_CYCLE_UPDATE_FAILED = 'BILLING_CYCLE:UPDATE_FAILED';
export const BILLING_CYCLE_DELETE = 'BILLING_CYCLE:DELETE';
export const BILLING_CYCLE_DELETE_SUCCESS = 'BILLING_CYCLE:DELETE_SUCCESS';
export const BILLING_CYCLE_DELETE_FAILED = 'BILLING_CYCLE:DELETE_FAILED';

// PACKAGE MODULE
export const PACKAGE_LOAD = 'PACKAGE:LOAD';
export const PACKAGE_LOAD_SUCCESS = 'PACKAGE:LOAD_SUCCESS';
export const PACKAGE_LOAD_FAILED = 'PACKAGE:LOAD_FAILED';
export const PACKAGE_CREATE = 'PACKAGE:CREATE';
export const PACKAGE_CREATE_SUCCESS = 'PACKAGE:CREATE_SUCCESS';
export const PACKAGE_CREATE_FAILED = 'PACKAGE:CREATE_FAILED';
export const PACKAGE_UPDATE = 'PACKAGE:UPDATE';
export const PACKAGE_UPDATE_SUCCESS = 'PACKAGE:UPDATE_SUCCESS';
export const PACKAGE_UPDATE_FAILED = 'PACKAGE:UPDATE_FAILED';
export const PACKAGE_DELETE = 'PACKAGE:DELETE';
export const PACKAGE_DELETE_SUCCESS = 'PACKAGE:DELETE_SUCCESS';
export const PACKAGE_DELETE_FAILED = 'PACKAGE:DELETE_FAILED';

// SUBSCRIPTION MODULE
export const SUBSCRIPTION_LOAD = 'SUBSCRIPTION:LOAD';
export const SUBSCRIPTION_LOAD_SUCCESS = 'SUBSCRIPTION:LOAD_SUCCESS';
export const SUBSCRIPTION_LOAD_FAILED = 'SUBSCRIPTION:LOAD_FAILED';
export const SUBSCRIPTION_CREATE = 'SUBSCRIPTION:CREATE';
export const SUBSCRIPTION_CREATE_SUCCESS = 'SUBSCRIPTION:CREATE_SUCCESS';
export const SUBSCRIPTION_CREATE_FAILED = 'SUBSCRIPTION:CREATE_FAILED';
export const SUBSCRIPTION_UPDATE = 'SUBSCRIPTION:UPDATE';
export const SUBSCRIPTION_UPDATE_SUCCESS = 'SUBSCRIPTION:UPDATE_SUCCESS';
export const SUBSCRIPTION_UPDATE_FAILED = 'SUBSCRIPTION:UPDATE_FAILED';
export const SUBSCRIPTION_DELETE = 'SUBSCRIPTION:DELETE';
export const SUBSCRIPTION_DELETE_SUCCESS = 'SUBSCRIPTION:DELETE_SUCCESS';
export const SUBSCRIPTION_DELETE_FAILED = 'SUBSCRIPTION:DELETE_FAILED';

// INVOICE MODULE
export const INVOICE_LOAD = 'INVOICE:LOAD';
export const INVOICE_LOAD_SUCCESS = 'INVOICE:LOAD_SUCCESS';
export const INVOICE_LOAD_FAILED = 'INVOICE:LOAD_FAILED';
export const INVOICE_CREATE = 'INVOICE:CREATE';
export const INVOICE_CREATE_SUCCESS = 'INVOICE:CREATE_SUCCESS';
export const INVOICE_CREATE_FAILED = 'INVOICE:CREATE_FAILED';
export const INVOICE_UPDATE = 'INVOICE:UPDATE';
export const INVOICE_UPDATE_SUCCESS = 'INVOICE:UPDATE_SUCCESS';
export const INVOICE_UPDATE_FAILED = 'INVOICE:UPDATE_FAILED';
export const INVOICE_DELETE = 'INVOICE:DELETE';
export const INVOICE_DELETE_SUCCESS = 'INVOICE:DELETE_SUCCESS';
export const INVOICE_DELETE_FAILED = 'INVOICE:DELETE_FAILED';

// MESSAGE MODULE
export const MESSAGE_LOAD = 'MESSAGE:LOAD';
export const MESSAGE_LOAD_SUCCESS = 'MESSAGE:LOAD_SUCCESS';
export const MESSAGE_LOAD_FAILED = 'MESSAGE:LOAD_FAILED';
export const MESSAGE_CREATE = 'MESSAGE:CREATE';
export const MESSAGE_CREATE_SUCCESS = 'MESSAGE:CREATE_SUCCESS';
export const MESSAGE_CREATE_FAILED = 'MESSAGE:CREATE_FAILED';
export const MESSAGE_UPDATE = 'MESSAGE:UPDATE';
export const MESSAGE_UPDATE_SUCCESS = 'MESSAGE:UPDATE_SUCCESS';
export const MESSAGE_UPDATE_FAILED = 'MESSAGE:UPDATE_FAILED';
export const MESSAGE_DELETE = 'MESSAGE:DELETE';
export const MESSAGE_DELETE_SUCCESS = 'MESSAGE:DELETE_SUCCESS';
export const MESSAGE_DELETE_FAILED = 'MESSAGE:DELETE_FAILED';

// ALERT MODULE
export const ALERT_LOAD = 'ALERT:LOAD';
export const ALERT_LOAD_SUCCESS = 'ALERT:LOAD_SUCCESS';
export const ALERT_LOAD_FAILED = 'ALERT:LOAD_FAILED';
export const ALERT_CREATE = 'ALERT:CREATE';
export const ALERT_CREATE_SUCCESS = 'ALERT:CREATE_SUCCESS';
export const ALERT_CREATE_FAILED = 'ALERT:CREATE_FAILED';
export const ALERT_UPDATE = 'ALERT:UPDATE';
export const ALERT_UPDATE_SUCCESS = 'ALERT:UPDATE_SUCCESS';
export const ALERT_UPDATE_FAILED = 'ALERT:UPDATE_FAILED';
export const ALERT_DELETE = 'ALERT:DELETE';
export const ALERT_DELETE_SUCCESS = 'ALERT:DELETE_SUCCESS';
export const ALERT_DELETE_FAILED = 'ALERT:DELETE_FAILED';

// SETTING MODULE
export const SETTING_LOAD = 'SETTING:LOAD';
export const SETTING_LOAD_SUCCESS = 'SETTING:LOAD_SUCCESS';
export const SETTING_LOAD_FAILED = 'SETTING:LOAD_FAILED';
export const SETTING_UPDATE = 'SETTING:UPDATE';
export const SETTING_UPDATE_SUCCESS = 'SETTING:UPDATE_SUCCESS';
export const SETTING_UPDATE_FAILED = 'SETTING:UPDATE_FAILED';

// PROFILE MODULE
export const PROFILE_LOAD = 'PROFILE:LOAD';
export const PROFILE_LOAD_SUCCESS = 'PROFILE:LOAD_SUCCESS';
export const PROFILE_LOAD_FAILED = 'PROFILE:LOAD_FAILED';
export const PROFILE_UPDATE = 'PROFILE:UPDATE';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE:UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILED = 'PROFILE:UPDATE_FAILED';

// ACTIVITY MODULE
export const ACTIVITY_LOAD = 'ACTIVITY:LOAD';
export const ACTIVITY_LOAD_SUCCESS = 'ACTIVITY:LOAD_SUCCESS';
export const ACTIVITY_LOAD_FAILED = 'ACTIVITY:LOAD_FAILED';
export const ACTIVITY_CLEAR = 'ACTIVITY:CLEAR';
export const ACTIVITY_CLEAR_SUCCESS = 'ACTIVITY:CLEAR_SUCCESS';
export const ACTIVITY_CLEAR_FAILED = 'ACTIVITY:CLEAR_FAILED';

// ATTENDANCE MODULE
export const ATTENDANCE_LOAD = 'ATTENDANCE:LOAD';
export const ATTENDANCE_LOAD_SUCCESS = 'ATTENDANCE:LOAD_SUCCESS';
export const ATTENDANCE_LOAD_FAILED = 'ATTENDANCE:LOAD_FAILED';
export const ATTENDANCE_CREATE = 'ATTENDANCE:CREATE';
export const ATTENDANCE_CREATE_SUCCESS = 'ATTENDANCE:CREATE_SUCCESS';
export const ATTENDANCE_CREATE_FAILED = 'ATTENDANCE:CREATE_FAILED';

// NOTIFICATION MODULE
export const NOTIFICATION_SHOW = 'NOTIFICATION:SHOW';
export const NOTIFICATION_HIDE = 'NOTIFICATION:HIDE';
export const NOTIFICATION_REMOVE = 'NOTIFICATION:REMOVE';
